%YAML 1.2
---

#CAMERA
Camera_FPS        : 30

#VO
Featurepoint_coe  : 2
Featurepoint_max  : 50.0
Goodmatch_thresh  : 8
Chi2_thresh       : 15.991
Optim_round       : 10

#Map
Voxel_size        : 100.0

