%YAML 1.2
---

#CAMERA
UseXtionGen       : 1
Fps               : 30
ImgHeight         : 240
ImgWidth          : 320
InnerCx           : 160.5912
InnerCy           : 120.4792
InnerFx           : 253.0589
InnerFy           : 254.1649
DepthScale        : 10.0

#VO
FeatureNum        : 1000
ScaleFactor       : 1.2
LevelNum          : 8
IniThFAST         : 20
MinThFAST         : 7

#Map
Voxel_size        : 100.0

#FeatureMatching
Threshold         : 50
NNRatio           : 0.6

#KeyFrame
MaxGoodPointThres : 100
MaxFramesBetween  : 30
MinFramesBetween  : 8
